/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.nextuxs.ovc;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int btn_dump_laden=0x7f040002;
        public static final int lin=0x7f040000;
        public static final int textview=0x7f040001;
        public static final int tv_banned=0x7f040009;
        public static final int tv_company=0x7f040008;
        public static final int tv_expdate=0x7f040005;
        public static final int tv_gebdatum=0x7f040007;
        public static final int tv_kaartnummer=0x7f040004;
        public static final int tv_saldo=0x7f040003;
        public static final int tv_type=0x7f040006;
    }
    public static final class layout {
        public static final int main=0x7f020000;
        public static final int ovc=0x7f020001;
        public static final int sector_list=0x7f020002;
    }
    public static final class string {
        public static final int already_keys=0x7f03000a;
        public static final int app_name=0x7f030000;
        public static final int banned=0x7f030016;
        public static final int card_id=0x7f030011;
        public static final int card_type=0x7f030013;
        public static final int clear_db=0x7f03000e;
        public static final int company=0x7f030015;
        public static final int copy_db_2_sd=0x7f03000f;
        /**  ovc 
 ovc //
         */
        public static final int credit=0x7f030010;
        public static final int done=0x7f030007;
        public static final int error_no_key=0x7f03001c;
        public static final int error_readblock=0x7f030019;
        public static final int error_see_log=0x7f03001b;
        public static final int expdate=0x7f030012;
        public static final int expert=0x7f03000c;
        public static final int gebdatum=0x7f030014;
        public static final int import_keys=0x7f030009;
        public static final int incorrect_key=0x7f03001a;
        public static final int load_dump=0x7f030005;
        public static final int log_tag=0x7f030001;
        /**  error messages 
 error messages //
         */
        public static final int no_nfc=0x7f030017;
        public static final int not_enabled=0x7f030018;
        public static final int now_what=0x7f030008;
        public static final int or=0x7f030006;
        /**  app 
 app //
         */
        public static final int place_card=0x7f030002;
        public static final int please_wait=0x7f030004;
        public static final int reading_card=0x7f030003;
        public static final int save=0x7f03000d;
        public static final int simple=0x7f03000b;
    }
}
